name: dailyexpenses
description: Project Daily Expense.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.6
  intl: ^0.18.1
  get_storage: ^2.1.1
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.7
  lottie: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/